server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-personal
              uri: lb://ms-personal
              predicates:
                - Path=/personal/**
            - id: ms-especialidades
              uri: lb://ms-personal
              predicates:
                - Path=/especialidades/**
            - id: ms-consultorios
              uri: lb://ms-horarios
              predicates:
                - Path=/consultorios/**
            - id: ms-programacion-horarios
              uri: lb://ms-horarios
              predicates:
                - Path=/programacion-horarios/**
            - id: ms-pacientes
              uri: lb://ms-pacientes
              predicates:
                - Path=/pacientes/**
            - id: ms-medicamentos
              uri: lb://ms-farmacia
              predicates:
                - Path=/medicamentos/**
            - id: ms-examenes
              uri: lb://ms-laboratorio
              predicates:
                - Path=/examenes/**
            - id: ms-examenes-autorizados
              uri: lb://ms-laboratorio
              predicates:
                - Path=/examenes-autorizados/**
            - id: ms-historias
              uri: lb://ms-historias-clinicas
              predicates:
                - Path=/historias/**
            - id: ms-episodios
              uri: lb://ms-historias-clinicas
              predicates:
                - Path=/episodios/**
            - id: ms-recetas
              uri: lb://ms-historias-clinicas
              predicates:
                - Path=/recetas/**
            - id: ms-ordenes
              uri: lb://ms-historias-clinicas
              predicates:
                - Path=/ordenes/**
            - id: ms-adendas
              uri: lb://ms-historias-clinicas
              predicates:
                - Path=/adendas/**
            - id: ms-citas
              uri: lb://ms-citas
              predicates:
                - Path=/citas/**
            - id: ms-atencion-medica
              uri: lb://ms-atencion-medica
              predicates:
                - Path=/atenciones/**
            - id: ms-pagos-consulta
              uri: lb://ms-caja
              predicates:
                - Path=/pagos-consulta/**
            - id: ms-proformas
              uri: lb://ms-caja
              predicates:
                - Path=/proformas/**
            - id: ms-notas-credito
              uri: lb://ms-caja
              predicates:
                - Path=/notas-credito/**
            - id: ms-tarifas-consulta
              uri: lb://ms-caja
              predicates:
                - Path=/tarifas-consulta/**
            - id: ms-comprobantes
              uri: lb://ms-caja
              predicates:
                - Path=/comprobantes/**
            - id: ms-retiros-nota-credito
              uri: lb://ms-caja
              predicates:
                - Path=/retiros-nota-credito/**
            - id: ms-notificaciones
              uri: lb://ms-notificaciones
              predicates:
                - Path=/notificaciones/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/clinica-interno/protocol/openid-connect/certs
