# Configuración compartida por todos los microservicios
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  rabbitmq:
    host: rabbitmq-clinica
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:change-me-rabbitmq}
